### ISSUE TITLE
create emitter plugins

### ISSUE THREAD

**Issue by sahilsuneja1** [cloudviz/agentless-system-crawler#191]
## Debugging Commands Output

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Output of `python --version`:**

```
(paste your output here)
```

**Output of `pip freeze`:**

```
(paste your output here)
```

**Comment by ricarkol** [comment]
@sahilsuneja1 right now the emitters are classes, but they are very very close to be actual plugins. Do you think they are enough as they are now? and if not, would you be able to handle making them actual plugins?

**Comment by sahilsuneja1** [comment]
@ricarkol: Okay, I'll take a shot.
