### ISSUE TITLE
get_feature() for redis should return feature_key

### ISSUE THREAD

**Issue by sahilsuneja1** [cloudviz/agentless-system-crawler#240]
## Description

`get_feature()` in `redis_container_crawler.py` and `redis_host_crawler.py` should return `'feature_key' ('redis')` and not `'feature_type' ('application')`, as in the nginx plugin.

## Debugging Commands Output

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Output of `python --version`:**

```
(paste your output here)
```

**Output of `pip freeze`:**

```
(paste your output here)
```

**Comment by sahilsuneja1** [comment]
Please confirm @tatsuhirochiba

**Comment by tatsuhirochiba** [comment]
OK, I understand. I will fix it asap.
