### ISSUE TITLE
Add a new sas-emitter plugin

### ISSUE THREAD

**Issue by nadgowdas** [cloudviz/agentless-system-crawler#279]
## Description
Add new *SAS - k8s * Emitter plugin.

This plugin should have following functions:
1) Read token information from k8s secrets
(token, cloud-oe and access-group)

2) This will be a extension to `https` emitter

3) Populate _token_ and _cloud-oe_ in the https header `X-Auth-Token` and `Cloud-OE-ID` resp. 

4) Add  `access-group`, `namespace`, `features`, `source-type`, `timestamp` as query parameters

Sample send-frame api should look like:
```
curl -XPOST 'https://XXX:16100/sas/api/send-frame?access_group=d5043717-ac4b-4316-9c79-d771251aae0a&namespace=10.1.2.3/some_one&features=os,package,disk,config,file&timestamp=2017-02-27T13:32:05+0000&source_type=container' -H 'Content-Type: application/csv' -H 'Cloud-OE-ID: bluemix' -H 'X-Auth-Token: token-abc' -d @frames.txt
```

@canturkisci @niltonb ^^

**Comment by hitomitak** [comment]
@nadgowdas I want to change 2 points for sas emitter code. 1. Passing token by extraMetadata, 2. Switching On/Off of ssl verification 

1. Passing token by extraMetadata
If extraMetadata is not set, we use file data as sas token, but if set, we use it as a token. In our environment, we need to run multiple crawlers on the same host and use the different token for each crawler. So we easy to use sas emitter if we can pass the token by extraMetadata 

1. Switching On/Off of ssl verification. 
We use a self-signed certificate in our development environment and ssl verification is failed in requests.post function. So we want to change on/off of ssl verification for requests.post argument. One new option will be add to crawler.conf to switch it. 

If there is no problem, I will add code to sas emitter and create PR. How do you think?

**Comment by nadgowdas** [comment]
@hitomitak 
1) Passing token by extraMetadata
I think passing as extraMetadata in not secure way to pass tokens. Also, if your token changes (it expires and new token is created) you will have to restart crawler ?
To your use-case, you can still use current mechanism of `secret` file mounting. You can push multiple secrets to k8s (lets say secret1, secret2 etc.) Then when you start multiple crawlers you can mount the right secret in each crawler instance. 

Do you think this will work for me ?

2) Switching On/Off of ssl verification.  
Yes, I agree. You can make it a crawler conf and implement this change.

**Comment by hitomitak** [comment]
@nadgowdas  Thank you for a nice suggestion. Indeed, my idea is not secure. If the token is passed by extraMetadata, we can see the token by ps commands... I will push secrets to k8s and run crawlers. For ssl verification option, I will add a few lines to sas emitter and create PR. It is OK to not work for this.

**Comment by nadgowdas** [comment]
PR #302 and #287 has addressed this issue and merged to master.
