### ISSUE TITLE
Cleanup the requirements.txt files

### ISSUE THREAD

**Issue by ricarkol** [cloudviz/agentless-system-crawler#32]
We should have only one requirements.txt file at the root of the repo.

**Comment by MHBauer** [comment]
I would suggest one for the 'build and run' dependencies, and one for the 'test' dependencies that references the original. That way we don't make people download pytest and simplejson if they don't need it.

As reference, an example project which I am vaguely familiar with is https://github.com/GoogleCloudPlatform/PerfKitBenchmarker

**Comment by MHBauer** [comment]
lawlz, a comment closed this on accident.
