### ISSUE TITLE
sas-emitter plugin enhancement for registry crawler

### ISSUE THREAD

**Issue by tatsuhirochiba** [cloudviz/agentless-system-crawler#329]
## Description

Current sas-emitter automatically set `source_type` as crawler generated `system_type` (e.g. `container`). However, in registry crawler, sas wants to set `source_type` as `image` instead of  `container`. 

I think we can change `source_type` value by reading sas-secrets similar to other sas emitter specific settings in `crawler.conf`.

**Comment by nadgowdas** [comment]
PR #330 Merged. Closing
