### ISSUE TITLE
Would you consider a Python 3 version that leveragies asyncio?

### ISSUE THREAD

**Issue by cclauss** [cloudviz/agentless-system-crawler#40]
Is the crawler waiting more for IO or it could CPU bound?

If the former, then [asyncio](https://docs.python.org/3/library/asyncio.html) might greatly simplify the code vs. the current multiprocessing approach which is generally more focused on CPU bound workloads.  Python 2 support expires 3.5 years from now so porting ASC to Py3 would also help its longevity.

**Comment by ricarkol** [comment]
Hi @cclauss , crawling some features like files, config, and packages is definitely IO bound. Python 3 should help with that as you say.

**Comment by canturkisci** [comment]
closing this as this is now part of #142 , but some useful argument here.
