### ISSUE TITLE
make crawler (docker) event driven

### ISSUE THREAD

**Issue by nadgowdas** [cloudviz/agentless-system-crawler#51]
# Problem:

In the current system, crawler polls periodically to discover if any new container is created or existing container is deleted. If some container is created and deleted in-between this polling period, it would not be able to snapshot that container.
# Propose Solution:

make crawler event-driven or more precisely interruptible. Register for docker events (externally in docker client) and when a new container is created, it gets interrupted and snapshot them immediately.

**Comment by ricarkol** [comment]
dup of #208
