### ISSUE TITLE
_publish_to_broker() is defined twice in crawler/emitter.py

### ISSUE THREAD

**Issue by cclauss** [cloudviz/agentless-system-crawler#56]
https://github.com/cloudviz/agentless-system-crawler/blob/master/crawler/emitter.py#L282

`flake8 . --count --exit-zero --max-line-length=127 --statistics | grep F811`

**Comment by MorganBauer** [comment]
@ricarkol possibly a latent merge error?

**Comment by MHBauer** [comment]
@ricarkol possibly a latent merge error?

**Comment by ricarkol** [comment]
removed the extra copy
