### ISSUE TITLE
push container image to dockerhub

### ISSUE THREAD

**Issue by MHBauer** [cloudviz/agentless-system-crawler#59]
either by using the automated builds provided by dockerhub, or through some other external mechanism.

I know @duglin has experience in hooking this up.

**Comment by canturkisci** [comment]
@nadgowdas i believe this is done w dockerhub/cloudviz ? 
Can we close it?

**Comment by nadgowdas** [comment]
@canturkisci yes, we can close it.

container image for crawler is being maintained at Docker Hub: https://hub.docker.com/r/cloudviz/agentless-system-crawler/

On Docker Hub, a build is configured to be triggered on  every master commit
