### ISSUE TITLE
Increase code coverage to >90%

### ISSUE THREAD

**Issue by ricarkol** [cloudviz/agentless-system-crawler#72]
That is right, not 88%, not 89.9%...

**Comment by duglin** [comment]
LOL

**Comment by MHBauer** [comment]
Happy Hacking!

**Comment by MHBauer** [comment]
Also need to figure out how to remove the test code from the test results. It's nice to know it's running, but deceptive that it increases the coverage.

**Comment by ricarkol** [comment]
That's done with a .coveragerc and adding an omit section:

```
[run]
source = __YOUR_PROJECT_FOLDER__

[report]
exclude_lines =
    if self.debug:
    pragma: no cover
    raise NotImplementedError
    if __name__ == .__main__.:
ignore_errors = True
omit =
    tests/*
```

Will add it in the next PR.

**Comment by ricarkol** [comment]
Finally, 90% of code coverage. Unit tests cover 80%. I feel confident enough with this 90% to start cleaning up code a bit more aggressively. Will try to make pylint, flakes happier. Closing this.
